import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
import { randomUUID } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import { request } from 'node:http';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
process.on('SIGPIPE', () => undefined);

const exec = promisify(execFile); const project = `jatoba-graph-${process.pid}-${Date.now()}`; const password = `graph-pass-${randomUUID()}`; const apiKey = `graph-key-${randomUUID()}`;
const env = { ...process.env, JATOBA_TEST_PASSWORD: password, JATOBA_TEST_API_KEY: apiKey, GRAPHIFY_BIN: 'graphify', RATE_LIMIT_ENABLED: 'true', RATE_LIMIT_MAX: '100000', RATE_LIMIT_MCP_MAX: '100000' };
const compose = (...args) => exec('docker', ['compose', '-p', project, '-f', 'docker-compose.test.yml', ...args], { env, maxBuffer: 10 * 1024 * 1024 });
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms)); const percentile = (values, p) => { const s = [...values].sort((a, b) => a - b); return Number(s[Math.min(s.length - 1, Math.ceil(s.length * p) - 1)].toFixed(2)); };
async function call(port, tool, input) { return new Promise((resolve) => { const start = performance.now(); const body = JSON.stringify(input); const req = request({ hostname: '127.0.0.1', port, path: `/api/tools/${tool}`, method: 'POST', timeout: 10000, headers: { 'content-type': 'application/json', 'content-length': Buffer.byteLength(body), 'x-jatoba-key': apiKey } }, (res) => { let text = ''; res.setEncoding('utf8'); res.on('data', (chunk) => { text += chunk; }); res.on('end', () => { let parsed; try { parsed = JSON.parse(text); } catch { parsed = null; } resolve({ ok: (res.statusCode ?? 0) < 400, status: res.statusCode ?? 0, body: parsed, ms: performance.now() - start }); }); }); req.on('timeout', () => req.destroy()); req.on('error', (error) => resolve({ ok: false, status: 0, error: error.message, ms: performance.now() - start })); req.end(body); }); }
async function main() {
  const report = { generated_at: new Date().toISOString(), indexing: [], query_load: [], concurrent_index: null, cross_repo_concurrency: null, stale: null, hybrid: null, classification: 'FAIL' };
  try {
    await compose('up', '-d', '--build'); const port = Number((await compose('port', 'brain', '3338')).stdout.trim().split(':').pop());
    for (let i = 0; i < 60; i += 1) { if ((await call(port, 'project_list', {})).ok) break; await sleep(500); }
    const fixture = await mkdtemp('/tmp/jatoba-graph-fixture-'); await writeFile(path.join(fixture, 'auth.ts'), 'export class AuthService { session() { return true } }\nexport class SessionStore { auth() { return new AuthService().session() } }\n'); await exec('git', ['init', '-q'], { cwd: fixture }); await exec('git', ['config', 'user.email', 'test@example.invalid'], { cwd: fixture }); await exec('git', ['config', 'user.name', 'GraphTest'], { cwd: fixture }); await exec('git', ['add', '.'], { cwd: fixture }); await exec('git', ['commit', '-qm', 'fixture'], { cwd: fixture }); await exec('docker', ['cp', `${fixture}/.`, `${project}-brain-1:/workspace/graph-small`]);
    const created = await call(port, 'project_create', { name: 'Graph Project', slug: `graph-${process.pid}`, workspace: 'graph-workspace' }); const projectId = created.body.id;
    const repo = await call(port, 'repository_add', { project: projectId, name: 'Graph Small', path: 'graph-small' }); const repositoryId = repo.body.id; const base = { project: projectId, repositoryId };
    const mediumFixture = await mkdtemp('/tmp/jatoba-graph-medium-'); await Promise.all(Array.from({ length: 180 }, (_, i) => writeFile(path.join(mediumFixture, `module-${i}.ts`), `import { AuthService } from './module-${(i + 1) % 180}.ts';\nexport class Module${i} { run() { return new AuthService().session(); } }\n`))); await exec('git', ['init', '-q'], { cwd: mediumFixture }); await exec('git', ['config', 'user.email', 'test@example.invalid'], { cwd: mediumFixture }); await exec('git', ['config', 'user.name', 'GraphTest'], { cwd: mediumFixture }); await exec('git', ['add', '.'], { cwd: mediumFixture }); await exec('git', ['commit', '-qm', 'medium fixture'], { cwd: mediumFixture }); await exec('docker', ['cp', `${mediumFixture}/.`, `${project}-brain-1:/workspace/graph-medium`]); const mediumRepo = await call(port, 'repository_add', { project: projectId, name: 'Graph Medium', path: 'graph-medium' }); const mediumBase = { project: projectId, repositoryId: mediumRepo.body.id };
    const indexStart = performance.now(); const indexed = await call(port, 'graph_index', base); report.indexing.push({ size: 'small', files: 1, ms: Number((performance.now() - indexStart).toFixed(2)), status: indexed.body?.status, http_status: indexed.status, response: indexed.body, nodes: indexed.body?.nodes_count ?? null, edges: indexed.body?.edges_count ?? null, bytes: indexed.body?.graph_path ? (await exec('docker', ['exec', `${project}-brain-1`, 'stat', '-c', '%s', indexed.body.graph_path])).stdout.trim() : null });
    const mediumStart = performance.now(); const indexedMedium = await call(port, 'graph_index', mediumBase); report.indexing.push({ size: 'medium', files: 180, ms: Number((performance.now() - mediumStart).toFixed(2)), status: indexedMedium.body?.status, response: indexedMedium.body, nodes: indexedMedium.body?.nodes_count ?? null, edges: indexedMedium.body?.edges_count ?? null, bytes: indexedMedium.body?.graph_path ? (await exec('docker', ['exec', `${project}-brain-1`, 'stat', '-c', '%s', indexedMedium.body.graph_path])).stdout.trim() : null }); if (indexedMedium.body?.status !== 'READY') report.medium_diagnostics = await exec('docker', ['logs', '--tail', '30', `${project}-brain-1`]).then((r) => r.stdout.trim()).catch((e) => `${e.stdout ?? ''}${e.stderr ?? ''}`);
    if (indexed.body.status !== 'READY') report.diagnostics = { command: 'graphify extract /workspace/graph-small --code-only --no-cluster --max-workers 2 --out /tmp/graph-debug', runtime_log: await exec('docker', ['logs', '--tail', '30', `${project}-brain-1`]).then((r) => r.stdout.trim()).catch((e) => `${e.stdout ?? ''}${e.stderr ?? ''}`), cwd: await exec('docker', ['exec', `${project}-brain-1`, 'pwd']).then((r) => r.stdout.trim()).catch((e) => e.message), identity: await exec('docker', ['exec', `${project}-brain-1`, 'id']).then((r) => r.stdout.trim()).catch((e) => e.message), graphify_path: await exec('docker', ['exec', `${project}-brain-1`, 'sh', '-c', 'which graphify && graphify --version']).then((r) => r.stdout.trim()).catch((e) => e.message), python: await exec('docker', ['exec', `${project}-brain-1`, 'python3', '--version']).then((r) => r.stdout.trim()).catch((e) => e.message), paths: await exec('docker', ['exec', `${project}-brain-1`, 'sh', '-c', 'ls -ld /workspace /workspace/graph-small /app/graphs; git -C /workspace/graph-small status --porcelain']).then((r) => r.stdout.trim()).catch((e) => `${e.stdout ?? ''}${e.stderr ?? ''}`), manual: await exec('docker', ['exec', `${project}-brain-1`, 'sh', '-c', 'rm -rf /tmp/graph-debug; graphify extract /workspace/graph-small --code-only --no-cluster --max-workers 2 --out /tmp/graph-debug >/tmp/graph-debug.stdout 2>/tmp/graph-debug.stderr; code=$?; printf "exit=%s\\n" "$code"; cat /tmp/graph-debug.stderr; find /tmp/graph-debug -maxdepth 3 -type f -printf "%p %s bytes\\n"']).then((r) => r.stdout.trim()).catch((e) => `${e.stdout ?? ''}${e.stderr ?? ''}`) };
    const statusReady = await call(port, 'graph_status', base); report.stale = { ready: statusReady.body.status };
    const queryRuns = [];
    for (const concurrency of [1, 5, 10, 25]) { const results = []; let next = 0; const started = performance.now(); const worker = async () => { while (true) { const i = next++; if (i >= 40) return; results.push(await call(port, ['graph_status', 'graph_query', 'graph_neighbors', 'graph_impact'][i % 4], { ...base, query: 'AuthService', entity: 'AuthService', depth: 1, max_nodes: 20, max_edges: 30 })); } }; await Promise.all(Array.from({ length: concurrency }, worker)); const elapsed = (performance.now() - started) / 1000; queryRuns.push({ concurrency, operations: results.length, errors: results.filter((r) => !r.ok).length, error_rate: Number((results.filter((r) => !r.ok).length / results.length).toFixed(4)), p50_ms: percentile(results.map((r) => r.ms), .5), p95_ms: percentile(results.map((r) => r.ms), .95), p99_ms: percentile(results.map((r) => r.ms), .99), rps: Number((results.length / elapsed).toFixed(2)) }); }
    report.query_load = queryRuns; const concurrent = await Promise.all([call(port, 'graph_index', base), call(port, 'graph_index', base)]); report.concurrent_index = concurrent.map((r) => r.body.status); const crossRepo = await Promise.all([call(port, 'graph_index', base), call(port, 'graph_index', mediumBase)]); report.cross_repo_concurrency = crossRepo.map((r) => r.body.status);
    await exec('docker', ['exec', `${project}-brain-1`, 'sh', '-c', "printf '\\nexport class NewDependency {}\\n' >> /workspace/graph-small/auth.ts"]); const stale = await call(port, 'graph_status', base); report.stale.after_change = stale.body.status;
    await exec('docker', ['exec', `${project}-brain-1`, 'sh', '-c', 'cd /workspace/graph-small && git -c safe.directory=/workspace/graph-small add auth.ts && git -c safe.directory=/workspace/graph-small commit -qm update']); const reindexed = await call(port, 'graph_index', base); report.stale.after_reindex = reindexed.body.status; await call(port, 'remember', { project: projectId, repositoryId, type: 'FACT', content: 'AuthService session graph fixture context' }); const hybrid = await call(port, 'context_retrieve', { project: projectId, repositoryId, query: 'AuthService session', max_items: 10, include_structural_graph: true, include_work_graph: false, include_timeline: false }); report.hybrid = { ok: hybrid.ok, sources: hybrid.body?.sources?.map((source) => source.ref) ?? [] };
    report.classification = indexed.ok && report.query_load.every((r) => r.errors === 0) && report.stale.ready === 'READY' && report.stale.after_reindex === 'READY' ? 'PASS' : 'DEGRADED'; console.log(`GRAPH_RESULT ${JSON.stringify(report)}`);
  } finally { await compose('down', '-v', '--remove-orphans').catch(() => undefined); }
}
await main().catch((error) => { console.error(`GRAPH_FAILED ${error.stack ?? error.message}`); process.exitCode = 1; });
